// UP districts list
export const UP_DISTRICTS = [
  "आगरा",
  "अलीगढ़",
  "अंबेडकर नगर",
  "अमेठी",
  "अमरोहा",
  "औरैया",
  "अयोध्या",
  "आज़मगढ़",
  "बागपत",
  "बहराइच",
  "बलिया",
  "बलरामपुर",
  "बाँदा",
  "बाराबंकी",
  "बरेली",
  "बस्ती",
  "भदोही",
  "बिजनौर",
  "बदायूँ",
  "बुलंदशहर",
  "चंदौली",
  "चित्रकूट",
  "देवरिया",
  "एटा",
  "एटावा",
  "फर्रुखाबाद",
  "फतेहपुर",
  "फिरोजाबाद",
  "गौतम बुद्ध नगर",
  "गाजियाबाद",
  "गाजीपुर",
  "गोंडा",
  "गोरखपुर",
  "हमीरपुर",
  "हापुड़",
  "हरदोई",
  "हाथरस",
  "जालौन",
  "जौनपुर",
  "झाँसी",
  "कानपुर देहात",
  "कानपुर नगर",
  "कासगंज",
  "कौशांबी",
  "कुशीनगर",
  "लखीमपुर खीरी",
  "ललितपुर",
  "लखनऊ",
  "महाराजगंज",
  "महोबा",
  "मैनपुरी",
  "मथुरा",
  "मऊ",
  "मेरठ",
  "मिर्जापुर",
  "मुरादाबाद",
  "मुजफ्फरनगर",
  "पीलीभीत",
  "प्रतापगढ़",
  "प्रयागराज",
  "रायबरेली",
  "रामपुर",
  "सहारनपुर",
  "संभल",
  "संत कबीर नगर",
  "शाहजहाँपुर",
  "शामली",
  "श्रावस्ती",
  "सिद्धार्थनगर",
  "सीतापुर",
  "सोनभद्र",
  "सुल्तानपुर",
  "उन्नाव",
  "वाराणसी",
];

export const TRUST_NAME = "माता कल्पना बाजपेई राष्ट्रीय सेवा ट्रस्ट";
export const TRUST_WEBSITE = "www.mkbrsevtrust.org";
export const TRUST_HELPLINE = "1800-XXX-XXXX";
export const TRUST_REG_NO = "MKBRST/2024/UP/001";

// UPI ID - Admin can update this from Admin Panel > CMS tab
export const DEFAULT_TRUST_UPI_ID = "mkbrseva@upi";

export const MEMBER_CHARGE = 110;

// Language labels
export const LANG = {
  hi: {
    login: "लॉगिन",
    signup: "अभी जुड़ें",
    admin: "Admin",
    home: "होम",
    about: "हमारे बारे में",
    register: "पंजीकरण",
    contact: "संपर्क",
    sahayata: "सहायता सेवाएँ",
    dashboard: "डैशबोर्ड",
    logout: "लॉगआउट",
    payment: "भुगतान करें",
    upiId: "UPI ID",
    payNow: "भुगतान करें",
    memberLogin: "सदस्य लॉगिन",
    memberSignup: "नया पंजीकरण",
    adminPanel: "Admin Panel",
  },
  en: {
    login: "Login",
    signup: "Join Now",
    admin: "Admin",
    home: "Home",
    about: "About Us",
    register: "Register",
    contact: "Contact",
    sahayata: "Support Services",
    dashboard: "Dashboard",
    logout: "Logout",
    payment: "Pay Now",
    upiId: "UPI ID",
    payNow: "Pay Now",
    memberLogin: "Member Login",
    memberSignup: "New Registration",
    adminPanel: "Admin Panel",
  },
};
